import "./globals.css";

export const metadata = {
  title: "BootyDribble",
  description: "Generated by Sniffer",
  colorScheme: "dark",
  creator: "bootysucker",
  type: "womanstinkfetish",
  bookmarks: ["NoseInHerBooty"],
  category: "PantyFetish",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>My Navingula</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
